# gen_enemy_proto_meshes.py — 절차적 적 형태 프로토 메시 생성 (보드: 절차적 적 형태 프로토타입)
# OBJ 2종을 생성한다. 요소(Element) ID는 UV.u 정수 타일로 인코딩: ElementId = floor(u).
# 머티리얼(Custom HLSL WPO)이 ID별로 자전/부유/공전을 준다 — 스켈레탈 애니·VAT 불필요.
#
#   1) SM_EnemyProto_Bipyramid : 오각 쌍뿔 셸(상/하 분리, 휴식 시 닫힘) + 내부 코어 구(약점 시각체)
#        element 0 = 상부 뿔, 1 = 하부 뿔, 2 = 코어 구
#   2) SM_EnemyProto_AtomCubes : 중앙 핵 큐브 + 전자 큐브 3개(궤도 초기 위치 배치, 공전은 머티리얼)
#        element 0 = 핵 큐브(껍질), 1..3 = 전자, 4 = 내부 코어 구(약점 시각체 — 쌍뿔의 element 2 와 같은 역할)
#        (전자 k의 궤도축/속도는 머티리얼 HLSL과 계약 — 아래 ORBITS 주석)
#
# 사용: python Scripts/gen_enemy_proto_meshes.py [출력폴더=Saved/EnemyProto]
# 단위 cm, +Z 상방. 임포트는 커맨드렛으로(라이브 에디터 파이썬 임포트 = 데드락, 메모리 참조).
import math, os, sys

def obj_writer():
    return {"v": [], "vt": [], "vn": [], "f": []}  # f = list of (vi, ti, ni) triples

def add_tri(m, p0, p1, p2, elem, vs=(0.2, 0.5, 0.8)):
    # 평면 노멀(플랫 셰이딩) + 요소 UV 타일
    ux, uy, uz = (p1[0]-p0[0], p1[1]-p0[1], p1[2]-p0[2])
    wx, wy, wz = (p2[0]-p0[0], p2[1]-p0[1], p2[2]-p0[2])
    nx, ny, nz = (uy*wz-uz*wy, uz*wx-ux*wz, ux*wy-uy*wx)
    l = math.sqrt(nx*nx+ny*ny+nz*nz) or 1.0
    n = (nx/l, ny/l, nz/l)
    base_v = len(m["v"]); base_t = len(m["vt"]); base_n = len(m["vn"])
    m["v"] += [p0, p1, p2]
    u0 = elem + 0.1; u1 = elem + 0.9
    m["vt"] += [(u0 + (u1-u0)*vs[0], 0.1), (u0 + (u1-u0)*vs[1], 0.9), (u0 + (u1-u0)*vs[2], 0.1)]
    m["vn"].append(n)
    m["f"].append(tuple((base_v+i+1, base_t+i+1, base_n+1) for i in range(3)))

def add_quad(m, p0, p1, p2, p3, elem):
    add_tri(m, p0, p1, p2, elem)
    add_tri(m, p0, p2, p3, elem)

def icosphere(m, center, r, elem):
    # 정이십면체 1회 세분(80삼각) — 코어 구
    t = (1.0 + math.sqrt(5.0)) / 2.0
    verts = [(-1,t,0),(1,t,0),(-1,-t,0),(1,-t,0),(0,-1,t),(0,1,t),(0,-1,-t),(0,1,-t),(t,0,-1),(t,0,1),(-t,0,-1),(-t,0,1)]
    def norm(p):
        l = math.sqrt(p[0]**2+p[1]**2+p[2]**2)
        return (p[0]/l, p[1]/l, p[2]/l)
    verts = [norm(v) for v in verts]
    faces = [(0,11,5),(0,5,1),(0,1,7),(0,7,10),(0,10,11),(1,5,9),(5,11,4),(11,10,2),(10,7,6),(7,1,8),
             (3,9,4),(3,4,2),(3,2,6),(3,6,8),(3,8,9),(4,9,5),(2,4,11),(6,2,10),(8,6,7),(9,8,1)]
    def mid(a, b):
        return norm(((a[0]+b[0])/2, (a[1]+b[1])/2, (a[2]+b[2])/2))
    for (a, b, c) in faces:
        va, vb, vc = verts[a], verts[b], verts[c]
        ab, bc, ca = mid(va, vb), mid(vb, vc), mid(vc, va)
        for tri in [(va, ab, ca), (ab, vb, bc), (ca, bc, vc), (ab, bc, ca)]:
            pts = [(center[0]+p[0]*r, center[1]+p[1]*r, center[2]+p[2]*r) for p in tri]
            add_tri(m, pts[0], pts[1], pts[2], elem)

def cube(m, center, half, elem):
    cx, cy, cz = center
    h = half
    c = [(cx-h,cy-h,cz-h),(cx+h,cy-h,cz-h),(cx+h,cy+h,cz-h),(cx-h,cy+h,cz-h),
         (cx-h,cy-h,cz+h),(cx+h,cy-h,cz+h),(cx+h,cy+h,cz+h),(cx-h,cy+h,cz+h)]
    add_quad(m, c[0], c[3], c[2], c[1], elem)  # -Z
    add_quad(m, c[4], c[5], c[6], c[7], elem)  # +Z
    add_quad(m, c[0], c[1], c[5], c[4], elem)  # -Y
    add_quad(m, c[2], c[3], c[7], c[6], elem)  # +Y
    add_quad(m, c[1], c[2], c[6], c[5], elem)  # +X
    add_quad(m, c[3], c[0], c[4], c[7], elem)  # -X

def write_obj(m, path, name):
    with open(path, "w", encoding="ascii") as f:
        f.write(f"# FPSR enemy proto mesh: {name} (generated by gen_enemy_proto_meshes.py)\n")
        f.write(f"o {name}\n")
        for v in m["v"]:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        for t in m["vt"]:
            f.write(f"vt {t[0]:.5f} {t[1]:.5f}\n")
        for n in m["vn"]:
            f.write(f"vn {n[0]:.5f} {n[1]:.5f} {n[2]:.5f}\n")
        for face in m["f"]:
            f.write("f " + " ".join(f"{vi}/{ti}/{ni}" for (vi, ti, ni) in face) + "\n")
    print(f"[gen] {path}  (tris={len(m['f'])})")

def gen_bipyramid(out_dir):
    # 오각 쌍뿔: 적도 반경 50, 꼭짓점 ±75.
    #
    # GAP=0 = 휴식 자세에서 **닫힌** 껍질(사용자 결정 2026-08-25). 종전엔 z=±4로 벌려 적도 틈새로
    # 코어 빛을 노출했는데, 그러면 "쉬는 중"과 "공격 중"이 같은 실루엣이라 공격이 안 읽혔다. 이제
    # 벌어지는 것 자체가 공격 모션이다(머티리얼 ProcWPO 의 Attack 오버레이가 element 0/1 을 ±Z 로
    # 민다) — 조개가 입을 여는 것에 해당한다. 코어는 껍질이 반투명이라 닫힌 상태에서도 비쳐 보인다.
    #
    # ⚠️ 이 값을 0 이 아닌 값으로 되돌리면 C0-at-entry 계약이 깨진다: 휴식 변위가 0 이어야
    # 상태 진입/이탈에 팝이 없다(FPSRAnimCPDParams.h 계약).
    m = obj_writer()
    R, APEX, GAP = 50.0, 75.0, 0.0
    ring = [(R*math.cos(2*math.pi*i/5), R*math.sin(2*math.pi*i/5)) for i in range(5)]
    top, bot = (0.0, 0.0, APEX), (0.0, 0.0, -APEX)
    for i in range(5):
        a, b = ring[i], ring[(i+1) % 5]
        # 상부 뿔(element 0): 적도변 z=+GAP — 공격 시 머티리얼이 +Z 로 민다
        add_tri(m, (a[0], a[1], GAP), (b[0], b[1], GAP), top, 0)
        # 하부 뿔(element 1): 적도변 z=-GAP (와인딩 반대) — 공격 시 -Z
        add_tri(m, (b[0], b[1], -GAP), (a[0], a[1], -GAP), bot, 1)
    icosphere(m, (0.0, 0.0, 0.0), 20.0, 2)  # 코어(element 2)
    write_obj(m, os.path.join(out_dir, "SM_EnemyProto_Bipyramid.obj"), "SM_EnemyProto_Bipyramid")

def gen_atom_cubes(out_dir):
    # 핵 큐브(half 30) + 전자 큐브 3개(half 10, 궤도 반경 80 초기 위치).
    # ORBITS — 머티리얼 HLSL과의 계약(요소 k의 궤도축, 초기 위치는 축과 수직):
    #   e1: axis (0,0,1)              P0 (80,0,0)
    #   e2: axis (0,0.7071,0.7071)    P0 (80,0,0)
    #   e3: axis (0.7071,0,-0.7071)   P0 (0,80,0)
    m = obj_writer()
    cube(m, (0.0, 0.0, 0.0), 30.0, 0)
    cube(m, (80.0, 0.0, 0.0), 10.0, 1)
    cube(m, (80.0, 0.0, 0.0), 10.0, 2)
    cube(m, (0.0, 80.0, 0.0), 10.0, 3)
    # 코어 구(element 4, 사용자 결정 2026-08-25): 핵 큐브 안에 든 작은 구 — 쌍뿔의 element 2 와 같은
    # 역할이다. 껍질(핵 큐브)의 십자 창을 통해 비쳐 보인다. 껍질보다 확실히 작아야(30 vs 14) 창
    # 밖으로 삐져나오지 않는다. 마지막에 써야 반투명 그리기 순서상 껍질 위로 비친다(정렬 없음).
    icosphere(m, (0.0, 0.0, 0.0), 14.0, 4)
    write_obj(m, os.path.join(out_dir, "SM_EnemyProto_AtomCubes.obj"), "SM_EnemyProto_AtomCubes")

if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join("Saved", "EnemyProto")
    os.makedirs(out, exist_ok=True)
    gen_bipyramid(out)
    gen_atom_cubes(out)
